### PR TITLE
Remove snapshot tests

### PR DESCRIPTION
**Pull request by gshank**
resolves #
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Problem

Duplication of tests in core and dbt-postgres. 

### Solution

I'm working on a lot of snapshot tickets, and we don't want test duplication. Most of these tests look like config type tests, which logically could belong to core. If there are some that should be re-implemented in dbt-adapters, let me know and I can open a follow-up ticket.

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-postgres/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by colin-rogers-dbt** [comment]
I think we can just update the base snapshot tests in place to reference what we already have dbt-adapters: https://github.com/dbt-labs/dbt-adapters/tree/main/dbt-tests-adapter/dbt/tests/adapter/simple_snapshot

**Comment by gshank** [comment]
I can update it to pull in the dbt-adapters snapshot test.

**Comment by gshank** [comment]
Actually the dbt-tests-adapter test is already pulled in: tests/functional/shared_tests/test_simple_snapshot.py

**Review by colin-rogers-dbt — APPROVED** [review]
thanks for clearing this up!

**Pull request merged**
