### PR TITLE
Updating changie.yaml to add contributors and PR links

### LINKED ISSUE #109: Update changie config to match other repos
_Copied from https://github.com/dbt-labs/dbt-adapters/issues/219_

The .`changie` yaml config in `dbt-adapters` (and `dbt-postgres`):
- https://github.com/dbt-labs/dbt-adapters/blob/main/.changie.yaml
- https://github.com/dbt-labs/dbt-postgres/blob/main/.changie.yaml

Doesn't match the config in other repos, e.g.
- https://github.com/dbt-labs/dbt-core/blob/main/.changie.yaml
- https://github.com/dbt-labs/dbt-snowflake/blob/main/.changie.yaml

The changelog is missing nice things we have in other repositories, such as PR links and contributors.

This is separate (and simpler) work from the desire to produce separate changelogs for `dbt-adapters` and `dbt-tests-adapter`:
- https://github.com/dbt-labs/dbt-adapters/issues/206

### PR DESCRIPTION
**Pull request by leahwicz**
resolves #109 

### Problem
This updates changie so that we are able to display PR links. It also adds the ability to generate a contributor list when there are external contributors. Basically it matches what the Snowflake and Core repos are doing for changelog.

### Solution
Copied over the Snowflake .changie file and tweaked it with the correct repo name.

### Tested Locally
1. Created a fake unreleased change file for a dependabot PR 
2. Populated a fake Core team env var: `export CHANGIE_CORE_TEAM=dbeatty10`
3. Ran: `changie batch 1.3.4`
4. This file was generated with a PR link as well as a contributor list that excludes `dbeatty10` but includes other handles from existing unreleased changes: [1.3.4.md](https://github.com/user-attachments/files/16435601/1.3.4.md)

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-postgres/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Review by mikealfare — APPROVED** [review]
Thanks friend!

**Comment by mikealfare** [comment]
@leahwicz Mind running precommit hooks (or add the missing return at the end of the config file) for the code quality check?

**Comment by colin-rogers-dbt** [comment]
@leahwicz 🫶

**Comment by leahwicz** [comment]
> @leahwicz Mind running precommit hooks (or add the missing return at the end of the config file) for the code quality check?

Oh duh good catch. I forgot to install that. Done!

**Pull request merged**
